server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://db:5432/user_service
    username: '{cipher}c2a796dcbb7e5ce3d54cc24dd50a56a52f348b8432640b0d5e9a6e67e704eb10'
    password: '{cipher}b3d68c6cc71f7c63deb83a466c8ab139121b8dabb66a79927093742c67f5e543'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "spring.json.add.type.headers": false
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        register: true
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-id: ${spring.application.name}:${random.uuid}
        instance-host: host.docker.internal
        prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
